stages:
  preprocess:
    cmd: python src\preprocess.py
    deps:
    - data\raw\test.csv
    - data\raw\train.csv
    - src\preprocess.py
    outs:
    - data\processed\test.csv
    - data\processed\train.csv
